[package]
name = "pbr"
version = "1.0.4"
authors = ["Ariel Mashraki <ariel@mashraki.co.il>", "Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
description = "Console progress bar for Rust"
documentation = "http://a8m.github.io/pb/doc/pbr/index.html"
repository = "https://github.com/a8m/pb"
exclude = ["gif/", ".travis.yml"]
keywords = ["cli", "progress", "terminal", "pb"]
license = "MIT"

[dependencies]
libc = "0.2.106"
time = "0.3.4"
crossbeam-channel = "0.5.1"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.9"
features = ["wincon", "processenv", "winbase"]

[dev-dependencies]
rand = "0.8.4"
